CREATE TABLE TBL_CATEGORY
(CATEGORY_CODE NUMBER CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY,
 CATEGORY_NAME VARCHAR(20) CONSTRAINT UN_CATEGORY_NAME UNIQUE
                           CONSTRAINT NN_CATEGORY_NAME NOT NULL
 );


CREATE TABLE TBL_MUSIC(
MUSIC_CODE NUMBER PRIMARY KEY,
MUSIC_NAME VARCHAR(20) NOT NULL,
MUSIC_SINGER VARCHAR(20) NOT NULL,
CATEGORY_CODE NUMBER REFERENCES TBL_CATEGORY(CATEGORY_CODE) NOT NULL,
PLAYABLE_STATUS CHAR(5) CHECK(PLAYABLE_STATUS IN ('Y' , 'N')));

CREATE SEQUENCE SEQ_CATEGORY_CODE
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MUSIC_CODE
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

INSERT
INTO TBL_CATEGORY
(CATEGORY_CODE, CATEGORY_NAME)
VALUES
(SEQ_CATEGORY_CODE.NEXTVAL, '케이팝');

INSERT
INTO TBL_CATEGORY
(CATEGORY_CODE, CATEGORY_NAME)
VALUES
(SEQ_CATEGORY_CODE.NEXTVAL, '발라드');

INSERT
INTO TBL_CATEGORY
(CATEGORY_CODE, CATEGORY_NAME)
VALUES
(SEQ_CATEGORY_CODE.NEXTVAL, '힙합');

INSERT
INTO TBL_CATEGORY
(CATEGORY_CODE, CATEGORY_NAME)
VALUES
(SEQ_CATEGORY_CODE.NEXTVAL, '락');

INSERT
INTO TBL_CATEGORY
(CATEGORY_CODE, CATEGORY_NAME)
VALUES
(SEQ_CATEGORY_CODE.NEXTVAL, '알앤비');



INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '빨간맛', '레드벨벳',1,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '휘파람', '블랙핑크',1,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '다이너마이트', '방탄소년단',1,'Y');



INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '사라지네', '이상',2,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '꿈처럼', '벤',2,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, 'Why', '백아연',2,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '겁', '송민호',3,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '도망가', '송민호',3,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '마에스트로', '창모',3,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '낭만고양이', '체리필터',4,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '비밀번호486', '윤하',4,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '가끔', '크러쉬',5,'Y');

INSERT INTO TBL_MUSIC
(MUSIC_CODE, MUSIC_NAME, MUSIC_SINGER,CATEGORY_CODE,PLAYABLE_STATUS)
VALUES
(SEQ_MUSIC_CODE.NEXTVAL, '메테오', '창모',5,'Y');